ame: readyapi-testrunner

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  RunReadyApiTests:
    runs-on: ubuntu-latest
    steps:
    # checkout branch
    - uses: actions/checkout@main

    - name: Get ReadyAPI
   # run: echo Get ReadyAPI Installer  
     run: curl https://dl.eviware.com/ready-api/3.40.1.0/ReadyAPI-x64-3.40.1.exe -o ~/ReadyAPI-x64-3.40.1.exe
